Update bsock.h
Avoid linker conflicts:

```
duplicate symbol _msock_type in:
    .libs/libdsock_la-crlf.o
    .libs/libdsock_la-udp.o
duplicate symbol _bsock_type in:
    .libs/libdsock_la-blog.o
    .libs/libdsock_la-unix.o
ld: 15 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libdsock.la] Error 1
```